config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'users#new'
  get 'users/calendar', to: 'users#calendar'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/myschedules', to: 'schedules#myschedules', defaults: {format: :json}
  get '/roomschedules/:id', to: 'schedules#roomschedules', defaults: {format: :json}
  
  resources :users
  resources :rooms
  resources :schedules
end

app/models/user.rb
class User < ApplicationRecord
  has_many :schedules, dependent: :destroy
  
  before_save { self.email = email.downcase }
  validates :f_name, presence: true, length: { maximum: 50 }
  validates :l_name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX },
                  uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # 渡された文字列のハッシュを返す（パスワード作成の時と同じ）
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :ban_to_loggin_user, only: [:new, :create]
  
  # マイカレンダー
  def calendar
    @user = User.find(current_user.id)
    @schedules = @user.schedules.order(start_at: "ASC")
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "アカウント作成に成功しました"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private
    
    def user_params
      params.require(:user).permit(:f_name, :l_name, :email, :password,
                                     :password_confirmation)
    end
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        flash[:danger] = "アクセス権限がありません。"
        redirect_to rooms_path
      end
    end
    
    def ban_to_loggin_user
      if logged_in?
        flash[:danger] = "ログインは完了しています。"
        redirect_to current_user
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :l_name, "姓" %>
  <%= f.text_field :l_name, class: 'form-control' %>
  
  <%= f.label :f_name, "名" %>
  <%= f.text_field :f_name, class: 'form-control' %>
  
  <%= f.label :email, "メールアドレス" %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password, "パスワード" %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "パスワード確認" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_schedules_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">開始時間</th>
      <th scope="col">終了時間</th>
      <th scope="col">会議室名</th>
      <th scope="col"></th> <!-- 編集ボタン -->
    </tr>
  </thead>
  <tbody>
    <% @schedules.each do |schedule| %>
    <tr>
      <td><%= schedule.name %></td>
      <td><%= schedule.start_at.strftime("%Y年%m月%d日 %H:%M") %></td>
      <td><%= schedule.end_at.strftime("%Y年%m月%d日 %H:%M") %></td>
      <td><%= schedule.room.name %></td>
      <td><%= button_to "編集", edit_schedule_path(schedule), {method: :get, class: "btn-primary"} %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/calendar.html.erb
<div class="container">
  <h2>マイカレンダー</h2>
  <div class="w-75 pb-3">
    <div id="my-calendar"></div>
  </div>
  <%= render "schedules_table" %>
</div>

app/views/users/calender.html.erb
<h1>マイカレンダー</h1>
<div id="calendar"></div>

app/views/users/edit.html.erb
<% provide(:button_text, '保存') %>
<h1>プロフィールの編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/login_form.html.erb
<h2>Login Page</h2>
<p>hello</p>

app/views/users/new.html.erb
<% provide(:button_text, 'アカウントを作成') %>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2>マイページ</h2>
  <div class="row mb-3 mx-0">
    <div class="card col mr-2 p-0">
      <div class="card-header">
        姓
      </div>
      <div class="card-body">
        <%=  @user.l_name %>
      </div>
    </div>
    
    <div class="card col p-0">
      <div class="card-header">
        名
      </div>
      <div class="card-body">
        <%= @user.f_name %>
      </div>
    </div>
  </div>
  <div class="card p-0 mb-3">
    <div class="card-header">
      メールアドレス
    </div>
    <div class="card-body">
      <%= @user.email %>
    </div>
  </div>
  <%= button_to "編集", edit_user_path, {class: "btn-primary", method: :get} %>
</div>