config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'users#new'
  get 'users/calendar', to: 'users#calendar'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/myschedules', to: 'schedules#myschedules', defaults: {format: :json}
  get '/roomschedules/:id', to: 'schedules#roomschedules', defaults: {format: :json}
  
  resources :users
  resources :rooms
  resources :schedules
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :schedules, dependent: :destroy
  
  validates :name, presence: true, length: {maximum: 50}, uniqueness: true
  validates :price, presence: true, numericality: {less_than: 10000000}
  validates :capacity, presence: true, numericality: { greater_than: 0, less_than: 10000000 }
  validates :open_at, presence: true
  validates :close_at, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user
  
  def index
    @rooms = Room.all
  end
  
  # カレンダーを表示,カレンダー上をクリックすると予定を作成できるようにする
  def show
    @room = Room.find(params[:id])
    @schedules = @room.schedules.order(start_at: "ASC")
  end
  
  def new
    @room = Room.new
  end
  
  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:success] = "会議室の作成に成功しました。"
      redirect_to @room
    else
      render 'new'
    end
  end
  
  def edit
    @room = Room.find(params[:id])
    @room_name = @room.name
  end
  
  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(room_params)
      flash[:success] = "#{@room.name}が更新されました。"
      redirect_to @room
    else
      render 'edit'
    end
  end
  
  def destroy
    room = Room.find(params[:id])
    flash[:success] = "#{room.name} を消去しました。"
    room.destroy
    redirect_to rooms_path
  end
  
  private
    def room_params
      params.require(:room).permit(:name, :capacity, :price, :open_at, :close_at)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <%= render 'shared/room_error_messages', object: @room %>
  <%= f.label :name, "会議室名" %>
  <%= f.text_field :name, class: 'form-control' %>
  
  <%= f.label :capacity, "収容人数" %>
  <%= f.number_field :capacity, class: 'form-control' %>
  
  <%= f.label :price, "利用金額" %>
  <%= f.number_field :price, class: 'form-control' %>

  <%= f.label :open_at, "使用可能時間（開始）" %>
  <%= f.time_field :open_at, class: 'form-control' %>
  
  <%= f.label :close_at, "使用可能時間（終了）" %>
  <%= f.time_field :close_at, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/rooms/_schedules_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">開始時間</th>
      <th scope="col">終了時間</th>
      <th scope="col">会議室名</th>
      <th scope="col"></th> <!-- 編集ボタン -->
    </tr>
  </thead>
  <tbody>
    <% @schedules.each do |schedule| %>
    <tr>
      <td><%= schedule.name %></td>
      <td><%= schedule.start_at.strftime("%Y年%m月%d日 %H:%M") %></td>
      <td><%= schedule.end_at.strftime("%Y年%m月%d日 %H:%M") %></td>
      <td><%= schedule.room.name %></td>
      <% if current_user?(schedule.user) %>
        <td><%= button_to "編集", edit_schedule_path(schedule), {method: :get, class: "btn-primary"} %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/edit.html.erb
<% provide(:button_text, '編集を保存') %>
<div class="container">
  <h1><%= @room.name %> の編集</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render "form"%>
      <%= button_to "消去", @room, {class: "btn-danger", method: :delete, data: {confirm: "すでにされている予約も全て消去されます。本当に消去しますか？"}} %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="container">
  <div class="row mx-0">
    <h2 class="col">会議室一覧</h2>
    <%= button_to "会議室の新規登録", new_room_path, {method: :get, class: "btn-primary col"} %>
  </div>
  <% if @rooms %>
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th scope="col">会議室名</th>
          <th scope="col">収容人数</th>
          <th scope="col">利用金額</th>
          <th scope="col">使用可能時間</th>
          <th scope="col"></th> <!-- 編集ボタン -->
          <th scope="col"></th> <!-- カレンダーボタン -->
        </tr>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
        <tr>
          <th scope="row"><%= room.id %></th>
          <td><%= room.name %></td>
          <td><%= room.capacity %> 人</td>
          <td><%= room.price %>円</td>
          <td><%= room.open_at.strftime("%H:%M") %> ~ <%= room.close_at.strftime("%H:%M") %></td>
          <td><%= button_to "編集", edit_room_path(room), {method: :get, class: "btn-secondary", data: {"turbolinks" => false}} %></td>
          <td><%= button_to "カレンダー", room, {method: :get, class: "btn-primary"} %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="pt-3">
      <h2>会議室は登録されていません。</h2>
    </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<% provide(:button_text, '登録') %>
<h1>会議室の新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "rooms/form" %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container pb-4">
  <div class="row">
    <div class="col-md-8"><h2 class="border-bottom"><%= @room.name %></h2></div>
    <div class="col-md"><%= button_to "新規予約", new_schedule_path, {params: {room_id: @room.id}, method: :get, class: "btn-primary"} %></div>
  </div>
</div>

<div class="container">
  <div class="row mb-3">
    <div class="card col mr-1 p-0">
      <div class="card-header">
        収容人数
      </div>
      <div class="card-body">
        <%= @room.capacity %>
      </div>
    </div>
    
    <div class="card col mx-1 p-0">
      <div class="card-header">
        利用金額
      </div>
      <div class="card-body">
        <%= @room.price %>
      </div>
    </div>
    
    <div class="card col ml-1 p-0">
      <div class="card-header">
        使用可能時間
      </div>
      <div class="card-body">
        <%= @room.open_at.strftime("%H:%M") %> ~ <%= @room.close_at.strftime("%H:%M") %>
      </div>
    </div>
  </div>
  
  <div class="w-75 pb-3">
    <div id="calendar"></div>
  </div>

  <%= render "schedules_table" %>
</div>

<script>
  $(document).ready (function(){
    $('#calendar').fullCalendar({
      events: '/roomschedules/<%= @room.id %>'
    });
  });
</script>