config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'users#new'
  get 'users/calendar', to: 'users#calendar'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get '/myschedules', to: 'schedules#myschedules', defaults: {format: :json}
  get '/roomschedules/:id', to: 'schedules#roomschedules', defaults: {format: :json}
  
  resources :users
  resources :rooms
  resources :schedules
end

app/views/layouts/_navbar.html.erb
<% if logged_in? %>
  <% provide(:login_or_rooms, rooms_path) %>
<% else %>
  <% provide(:login_or_rooms, login_path) %>
<% end %>
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap navbar-expand-md p-0">
  <%= link_to "会議室予約システム", yield(:login_or_rooms) , class: "navbar-brand mr-0 ml-3" %>
  
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="ナビゲーションの切替">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav px-3 ml-auto">
        <% if logged_in? %>
          <li class="nav-item text-nowrap mr-2">
            <span class="navbar-text text-white"><%= current_user.l_name + " " + current_user.f_name%></span>
          </li>
          <li class="nav-item text-nowrap">
            <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item text-nowrap">
            <%= link_to "ログイン", login_path, method: :get, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to "会議室一覧", rooms_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "マイカレンダー", users_calendar_path, class: "nav-link", data: {"turbolinks" => false} %>
      </li>
      <li class="nav-item">
        <%= link_to "マイページ", current_user, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>会議室予約システム</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div class="container-fluid p-0">
      <%= render 'layouts/navbar' %>
      <div class="row">
        <% if logged_in? %>
        <%= render 'layouts/sidebar' %>
        <% end %>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="align-items-center pb-2 mb-3 border-bottom">
            <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
            <!-- デバック表示（本番環境では実行しない） -->
            <%= debug(params) if Rails.env.development? %>
          </div>
        </main>
      </div>
    </div>
  </body>
</html>